language: go

go:
  - 1.14.x
  - master

# Allow builds from tip to fail - they might be in an unstable state
jobs:
  allow_failures:
    - go: master

os:
  - linux
  - osx
  - windows

arch:
  - amd64
  - arm64

env:
  global:
    - GO111MODULE=on

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then CGO_ENABLED=0 go build -ldflags="-w -s" -o ew-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH.exe . ; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then CGO_ENABLED=0 go build -ldflags="-w -s" -o ew-$TRAVIS_OS_NAME-$TRAVIS_CPU_ARCH . ; fi
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: MGuUg7zCbUVxssP89Fwx3UtOWw0lViUofVxisRv5JqGau+UhF0Ybo0wn5qq2YSdUP2LPKM34uwTgvV1MJQS18BhE5Jol7subMb095gBfS9pAqcxSXmfm4mIBDlxXQj4jpqH2PkFG0T21QB/7rGO4GzjsHzXKnXV2ScPSuolGFniFTJfrnfBPlPMjIqgFJ9XB7mUeKri3JzCcDgMMIZC5yL++V5Pk76fWVTqdwxJR+3LrZCJPkN80hro6mdUhIrGtYnOI0DQ+UGz0+mH05u3gqb0w12C7MzOad6fVAIapB5pdeQWFF8YQ2ki87L5sZ0I5Sfxe5NSFdB+ptx+6CyhjlIB8uzl9WWQLhgBy2Qbgrf6BuKTPAOdqxq+q6mdPhEtXLeRuVGHXxvqe+a4TFhLwea4cnT4IZyiU53b7gGRBY5k54oUvzPChQGCVcm8U4fIPLVnVUb0hXVHto0kxKhRoF0GyccgXp+zT6KTanBy0NFO5h+Sjf47C5DXE8qLyv8zs/qQjn5dw0AfAOMh6gaK7+fs77ryDXBdWoBaJ3eIJLfDH4oHNcxm/ek8Ob8tQxt3EbFnrcRTUeBgqd8TRQ2bO/MpJrRXgTmvQnSuhFfmhJBprrmt5Jz3uavsHNYzRFmtKXYM3CPs/OlxihYhfKWs6vLIB/9JIZuN5sZxWTgX35UM=
  file_glob: true
  file: ew*
  skip_cleanup: true
  on:
    repo: kernle32dll/ew
    tags: true
    go: 1.14.x